# Generated by Django 4.2.2 on 2023-06-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('AnimalId', models.AutoField(primary_key=True, serialize=False)),
                ('AnimalName', models.CharField(max_length=100)),
                ('AnimalBreed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerUser',
            fields=[
                ('BuyerUserId', models.AutoField(primary_key=True, serialize=False)),
                ('BuyerUserName', models.CharField(max_length=100)),
                ('BuyerUserPassword', models.CharField(max_length=100)),
                ('BuyerUserLocation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerUser',
            fields=[
                ('SellerUserId', models.AutoField(primary_key=True, serialize=False)),
                ('SellerUserName', models.CharField(max_length=100)),
                ('SellerUserPassword', models.CharField(max_length=100)),
                ('SellerUserLocation', models.IntegerField()),
            ],
        ),
    ]
