# Generated by Django 4.2.2 on 2023-06-30 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalApp', '0002_animals_message_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('app_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_location', models.IntegerField()),
                ('user_is_seller', models.BooleanField()),
                ('user_pets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='AnimalApp.animals')),
            ],
        ),
    ]
