# Generated by Django 4.2.2 on 2023-06-30 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalApp', '0003_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_pets',
        ),
        migrations.AddField(
            model_name='animals',
            name='animal_owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='AnimalApp.appuser'),
        ),
        migrations.AddField(
            model_name='animals',
            name='is_sold',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='MessageReceiverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_receiver_id', to='AnimalApp.appuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='MessageSenderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender_id', to='AnimalApp.appuser'),
        ),
    ]
