# Generated by Django 4.2.2 on 2023-06-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('AnimalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_type', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photos', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageId', models.AutoField(primary_key=True, serialize=False)),
                ('IsRead', models.BooleanField()),
                ('MessageBody', models.CharField(max_length=50000)),
                ('MessageReceiverId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_receiver_id', to='users.user')),
                ('MessageSenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender_id', to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
