# Generated by Django 4.2.2 on 2023-07-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalApp', '0004_remove_appuser_user_pets_animals_animal_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'managed': False},
        ),
    ]
