# Generated by Django 4.2.2 on 2023-07-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalApp', '0005_alter_animals_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animals',
            table='animals',
        ),
    ]
